Model 2 with cabin alphabet and occupation
LM1398/Test_Notebook pull request #4
Opened 2021-08-22 06:02 UTC by LM1398

# Changes
- Added occupation to preprocessed data by taking prefix of name
- Added cabin alphabet (whether the cabin had an alphabet) since it seemed to affect survival

2021-08-22 23:41 UTC, atsushimemet requested changes
@LM1398 
コメントした箇所を修正して下さい。
また、[3.8 Comments and Docstrings](https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings)を読み、VSCodeの拡張機能であるdocstring generatorを使用しつつ、全ての関数にdocstringを記載して下さい。(英語で)

よろしくお願い致します。

2021-08-22 23:41 UTC, atsushimemet commented on model2_cabin_occ.py
> +    df["cabin_a"] = np.asarray(cabin_has_alph).reshape(-1, 1)
@LM1398 
np.asarrayを使用せずとも、df["cabin_a]を作成できます。
cabin_has_alphを代入するだけで良いです。

2021-08-22 23:41 UTC, atsushimemet commented on model2_cabin_occ.py
> +    df["occ"] = [name.split(",")[1].split(".")[0] for name in df["Name"]]
@LM1398 
occは敬称のことだと思うのですが、occとはどのような意味ですか?
(単純に私が知らないだけです。。。教えてもらえると助かります。)

2021-08-22 23:41 UTC, atsushimemet commented on model2_cabin_occ.py
> +    )
@LM1398 
train, testで同じ処理をしているので、for文でまとめましょう。

2021-08-22 23:41 UTC, atsushimemet commented on model3_parameter_tuning.py
> +    ).fit(X, y).best_params_
@LM1398 
返り値がありません。returnを使って返り値を生成して下さい。

2021-08-22 23:41 UTC, atsushimemet commented on model3_parameter_tuning.py
> +    ).fit(X, y).best_params_
@LM1398
返り値がありません。returnを使って返り値を生成して下さい。

2021-08-22 23:41 UTC, atsushimemet commented on model3_parameter_tuning.py
> +    ).fit(X, y).best_params_
@LM1398
返り値がありません。returnを使って返り値を生成して下さい。

2021-08-22 23:41 UTC, atsushimemet commented on model3_parameter_tuning.py
> +    ).fit(X, y).best_params_
@LM1398
返り値がありません。returnを使って返り値を生成して下さい。

2021-08-22 23:41 UTC, atsushimemet commented on model3_parameter_tuning.py
> +    ).fit(X, y).best_params_
@LM1398
返り値がありません。returnを使って返り値を生成して下さい。

2021-08-22 23:41 UTC, atsushimemet commented on model3_parameter_tuning.py
> +    rf_parameters(X_train, y_train)
@LM1398 
ここで返り値が返されていないので、下のVotingに代入されているモデルはチューニング前のモデルになってしまっています。

2021-08-22 23:41 UTC, atsushimemet commented on model3_parameter_tuning.py
> +    svc = modeling_cv(X_train, y_train, SVC, probability=True)
@LM1398 
ここは不要だと思いますが、いかがですか?
（下のチューニングされたモデルを使用したいのですよね?）

2021-08-23 00:14 UTC, LM1398 commented on model2_cabin_occ.py
> +    df["occ"] = [name.split(",")[1].split(".")[0] for name in df["Name"]]
occ は occupation, 職業です!  一応Mr Mrsは職業ではないのですが、他にcpt(captain), Major, rev(reverend)などがあったので、occというカテゴリーにしました。

2021-08-23 00:15 UTC, LM1398 commented on model2_cabin_occ.py
> +    df["cabin_a"] = np.asarray(cabin_has_alph).reshape(-1, 1)
修正しました。

2021-08-23 00:18 UTC, LM1398 commented on model3_parameter_tuning.py
> +    ).fit(X, y).best_params_
修正しました。

2021-08-23 00:18 UTC, LM1398 commented on model3_parameter_tuning.py
> +    ).fit(X, y).best_params_
修正しました。

2021-08-23 00:18 UTC, LM1398 commented on model3_parameter_tuning.py
> +    ).fit(X, y).best_params_
修正しました。

2021-08-23 00:19 UTC, LM1398 commented on model3_parameter_tuning.py
> +    ).fit(X, y).best_params_
修正しました。

2021-08-23 00:20 UTC, LM1398 commented on model2_cabin_occ.py
> +    df["cabin_a"] = np.asarray(cabin_has_alph).reshape(-1, 1)
修正しました。

2021-08-23 00:38 UTC, LM1398 commented on model3_parameter_tuning.py
> +    rf_parameters(X_train, y_train)
修正しました。

2021-08-23 00:41 UTC, LM1398 commented on model3_parameter_tuning.py
> +    svc = modeling_cv(X_train, y_train, SVC, probability=True)
はい！不要でした。lr_parametersで返り値をbest_estimatorにすることで、GridSearchが探してくれた一番いいパラメーターをそのままmodelとして使えました。これはもっと早く知りたかった。。検索不足です

2021-08-23 01:30 UTC, LM1398 commented on model2_cabin_occ.py
> +    )
修正しました。

2021-08-24 23:46 UTC, atsushimemet requested changes
@LM1398 
コメントした部分を修正して下さい。

2021-08-24 23:46 UTC, atsushimemet commented on model2_cabin_occ.py
> +# Has cabin alphabet(cabin_a) values and occupation (occ) code in preprocess
@LM1398 
この部分はModuleのdocstringです。[こちら](https://google.github.io/styleguide/pyguide.html#382-modules)を参考に修正して下さい。

2021-08-24 23:46 UTC, atsushimemet commented on model2_cabin_occ.py
> +    """Preprocessing the features in the DataFrame using scalers for better model predictions
大変わかりやすく、素晴らしい記述です。

2021-08-24 23:46 UTC, atsushimemet commented on model2_cabin_occ.py
> +    """Preprocessing the features in the DataFrame using scalers for better model predictions
@LM1398 
Docstring内の文章にはコロンをつけて下さい。

2021-08-24 23:46 UTC, atsushimemet commented on model2_cabin_occ.py
> +    """Preprocessing the features in the DataFrame using scalers for better model predictions
↑この箇所だけではなく、全てです。

2021-08-24 23:46 UTC, atsushimemet commented on model2_cabin_occ.py
> +    df["occ"] = [name.split(",")[1].split(".")[0] for name in df["Name"]]
関数名にoccがあり、docstring序盤でoccupationの記述があり、occという語句が何を意味しているのか明快です。
素晴らしい命名です。

2021-08-24 23:46 UTC, atsushimemet commented on model3_parameter_tuning.py
> +# Used GridSearchCV to tune parameters
@LM1398 
こちらも同様で、moduleのdocstringの形式に修正して下さい。

2021-08-24 23:46 UTC, atsushimemet commented on model3_parameter_tuning.py
> +            },
@LM1398 
このパラメータの部分は、別途configディレクトリ直下に切り出して、読み込む形式に変更しましょう。
#5 に記載したので、別途pull requestで対応しましょう。
土曜日に詳細を説明します。

2021-08-24 23:46 UTC, atsushimemet commented on model4_079186.py
> +    return df
@LM1398 
特徴量生成のスクリプトを別途切り出しましょう。
土曜日に詳細をお話しします。

2021-08-25 00:49 UTC, LM1398 commented on model2_cabin_occ.py
> +# Has cabin alphabet(cabin_a) values and occupation (occ) code in preprocess
修正しました。

2021-08-25 00:52 UTC, LM1398 commented on model2_cabin_occ.py
> +    df["occ"] = [name.split(",")[1].split(".")[0] for name in df["Name"]]
ありがとうございます！

2021-08-25 01:02 UTC, LM1398 commented on model3_parameter_tuning.py
> +# Used GridSearchCV to tune parameters
修正しました。

2021-08-25 04:38 UTC, LM1398 commented on model4_079186.py
> +    return df
切り出して別のpyファイルを作りました。

2021-08-25 12:27 UTC, atsushimemet commented on model2_cabin_occ.py
> +    """Preprocessing the features in the DataFrame using scalers for better model predictions
@LM1398
Docstring内の文章にはコロンをつけて下さい。
こちら誤りでした。すみません。コロンではなく、ピリオドです。

2021-08-26 00:31 UTC, LM1398 commented on model2_cabin_occ.py
> +    """Preprocessing the features in the DataFrame using scalers for better model predictions
修正しました。

2021-08-26 12:23 UTC, atsushimemet approved these changes

2021-08-26 12:23 UTC, merged